baseurl = "https://lipk.org"
languageCode = "zh-cn"
title = "lipk • 李鹏坤"
preserveTaxonomyNames = true
enableEmoji = true
disableRSS = false
publishDir = "docs"
# ignoreFiles = [ "2018-12-20-test.md" ]

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight = 1
[[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 2

[[menu.about]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.about]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.about]]
    name = "简历"
    url = "/vitae/"
    weight = 3

[[menu.vitae]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.vitae]]
    name = "关于"
    url = "/about/"
    weight = 2
[[menu.vitae]]
    name = "简历"
    url = "/vitae/"
    weight = 3

[[menu.blog]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.blog]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.blog]]
    name = "美食"
    url = "/food/"
    weight = 3

[[menu.food]]
    name = "返回"
    url = "/"
    weight = 1
[[menu.food]]
    name = "博客"
    url = "/blog/"
    weight = 2
[[menu.food]]
    name = "美食"
    url = "/food/"
    weight = 3

[params]
    description = "zsdycs; 执手对影成双; Personal website of Pengkun Lee; 李鹏坤的个人网站; lipk"
    footer = "&copy; 2018 - 2020 [执手对影成双](/)"
    slogan = "执手相看，对影成双"
    customJS = [
                "js/indentation-el.js",  # 缩进
                "js/mode.js",            # 模式
                "js/beaudar.js",         # 评论
                "js/math-code.js",       # code 
                "js/center-img.js",      # img
                "js/right-quote.js",     # 引用
                "js/no-highlight.js",    # 移除高亮
                "js/fix-footnote.js",    # 修改
                "js/external-link.js",   # <a> 添加 _blank
                "js/alt-title.js",       # <img> alt -> title
                "js/header-link.js",     # h1 h2 h3 添加锚点
                "js/reset-scrollTop.js", # 滚动到对应锚点
                "js/checkbox-list.js",    # 无序 checkbox list，listStyle = 'none'
                "js/toc-powerful.js",    # 目录
                ]
    author = '李鹏坤'
    githubContentURL = "http://github.com/zsdycs/lipk.org/edit/master/content/"
    edit = "编辑"
    license = "版权"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsCDN = "//cdn.jsdelivr.net/gh/highlightjs/cdn-release@10.1.1"
    highlightjsLang = ["JavaScript", "HTML", "Markdown", "SCSS", "CSS", "TypeScript", "Ruby", "Bash"]
    highlightjsThemeNight = "vs2015"
    highlightjsThemeDay = "github"
 [author]
    blog = '李鹏坤'

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ""
    footnoteReturnLinkContents = "↩"
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2